// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer/index.vue')['default']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    Menu: typeof import('./src/components/Menu/Menu.vue')['default']
    MenuButton: typeof import('./src/components/Menu/MenuButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
